### ISSUE TITLE
Movement is annoying.

### ISSUE THREAD

**Issue by GoogleFrog** [SpringCabal/LD35#63]
The starting wisp has annoying movement. If you tell it to go right, stop and then tell it to move left it moves a little right and does a small u-turn. This does not give me the usual arrow-key controlled movement that is common to other games so it breaks my expectations. I think it also hinders controllabiity and reveals that the wisp has a facing.

**Comment by gajop** [comment]
Regarding this issue and a few others, third person movement that I inherited+hacked from Area17/Gravitas has a lot of problems.
I wish there was a clean implementation that could be easily configured each time we opt to do a 3rd person wasd/arrow controlled game.

**Comment by GoogleFrog** [comment]
Did you disable turn inertia? Did you increase turn rate? I could probably fix this with a little fiddling around.

**Comment by smoth** [comment]
I had something like this in my Halloween project. what is the camera control gadget?
