### ISSUE TITLE
Mushroom man makes a blue trail.

### ISSUE THREAD

**Issue by GoogleFrog** [SpringCabal/LD35#69]
The mushroom man has started making a new trail. I do not know when this began. It occurs every time I switch into man mode.
![screen00005](https://cloud.githubusercontent.com/assets/1318249/14635949/0896e076-066c-11e6-9fee-a48dc9dbd55e.jpg)

**Comment by GoogleFrog** [comment]
Wisp also makes a blue trail.

**Comment by gajop** [comment]
I honestly can't tell if this was intentional or not. Part of me assumed the idea here was to give sense that we're a spirit entity even when in physical form, but I did considered it odd at times.
@Anarchid  ?

**Comment by Anarchid** [comment]
I wanted it to have spirit hair ribbons, that's intentional. I don't think it worked out too well.

**Comment by gajop** [comment]
OK, not something that _needs_ fixing then. Up to you if and how you want to address it - I don't think it's necessarily bad.
Closing.
